from datetime import date

DATASET_START = date(2025, 3, 1)
DATASET_END = date(2026, 8, 31)

DATA_FOLDER = "data"
RAW_DATA_FOLDER = f"{DATA_FOLDER}/raw"
PROCESSED_DATA_FOLDER = f"{DATA_FOLDER}/processed"
INTEGRATED_DATA_FOLDER = f"{DATA_FOLDER}/integrated"
FEATURE_DATA_FOLDER = f"{DATA_FOLDER}/features"
ANALYTICS_DATA_FOLDER = f"{DATA_FOLDER}/analytics"
EDA_OUTPUT_FOLDER = f"{DATA_FOLDER}/eda"
ML_DATA_FOLDER = f"{DATA_FOLDER}/ml"
REPORTS_FOLDER = f"{DATA_FOLDER}/reports"
MODEL_FOLDER = "models"
